---
title: "Tutorial-03"
# author: Kate Saunders
format: 
  html:
    toc: true
    css: ../../assets/tutorial.css
    embed-resources: true
  pdf:
    toc: true
editor: visual
---

## Creating your own plot crimes and plot masterpieces

### Overview

You will be working in pairs to create data visualisations in Power BI.

One of you will be a force for good, creating beautiful visualisations that adhere to the principles of graphical excellence, and the other will be a force of bad, trying to make visualisations that will make the tutors cry.

This builds on the last tutorial where you critiqued visualisations based on the principles of graphical excellence. But today, you will create your own and go from theory to practice.

### Learning Objectives

-   Develop skills creating data visualisations in Power BI

-   Further build your understanding of the principles of graphical excellence

### Preparation

-   Ensure you have followed the instructions and have already installed Power BI.

-   Make sure to have reviewed the Lecture 2 material

## Tasks

1.  After you pair up, download a dataset from Moodle for this tutorial.

2.  Load in your chosen data set into PowerBI and look at the default assignment of data types. Do they appear correct?

3.  Before you get started, take a few minutes to think about what types of visualisations in Power BI are well suited to visualising that type of data.

4.  Start by creating 2 - 3 basic plots in Power BI. Do this on your own computer, but make the same plots as each other.

5.  Now decide who wants to be the "good" visualiser and who wants to be the "bad" visualiser. Play scissors, paper, rock if you can't decide.

6.  Thinking about the principles of graphical excellence iterate upon the basic plots you created in Step 4, either making your visualisation beautiful or ugly depending on your assigned roll. We recommend purposefully do the opposite of each other! Try playing with visual elements like colour, shape, size, proportion and labels. You can also change the plot types.

## Wrap Up and Share

Upload the worst and the best plot you created together on the discussion forum. Be sure to share them in the same thread so people can tell which plots belong together. If your plots aren't perfect that's okay, share them anyway. This is all just practice and you can work on making them worse/better later.

## In Your Own Time

Do the opposite role! If you were "bad" - create a beautiful plot, and if you were "good" - create something truly bad.

<!-- ## Note -->

<!-- If you end up completing this tutorial in your own time and don't have a pair that's okay. Just decide which role you want to play and follow the same instructions as above. It will be important for everyone to complete part 7, as we will use your posts in the first assignment. -->

<!-- ##### Material developed by Dr. Kate Saunders -->

##### © Copyright 2025 Monash University
