---
title: "Tutorial 2"
# author: "Kate Saunders, Krisanat Anukarnsakulchularp and Janith Wanniarachchi."
format: 
  html:
    toc: true
    css: ../../assets/tutorial.css
    embed-resources: true
  pdf:
    toc: true
editor: visual
---

## Plot crimes and plot masterpieces

### Overview

Today you will be working in groups to critique data visualisations.

We recommend not using AI for these tasks. Discuss ideas as a group or get direction from the teaching team.

### Learning Objectives

-   Work in a team to consolidate your knowledge of graphical principles, visual encodings and visual hierarchy

-   Together critically assess and evaluate data visualisations

-   Share knowledge and opinions to understand differences in human perception and cultural lenses

-   Practice writing and sharing your analysis

<!-- Collaborate effectively, contributing to team performance and the achievement of collective goals, and demonstrate leadership where appropriate; -->

### Preparation

-   Make sure to have reviewed the Lecture 2 material.

-   Come ready to have fun and give opinions.

## Task

Your task is to choose two data visualisations and review those visualisations in your group.

(i) Choose one that would be typically described as ugly from the [data-is-ugly reddit thread](https://www.reddit.com/r/dataisugly/?rdt=33540), and

(ii) Choose another that would be typically described as beautiful from the [data-is-beautiful reddit thread](https://www.reddit.com/r/dataisbeautiful/).

Review these visualisations:

-   How well were the principles of graphical excellence were adhered to?

-   How effective were aspects of human perception used in the plot design?

-   Was the choice of colour appropriate for these visualisations?

-   Was the data represented in an appropriate way, or was the visualisation misleading?

-   Lastly, consider if the "rules" of data visualisation were broken - was there a good reason?

#### Beware

Some 'ugly' visualisations may have beautiful elements, and some 'beautiful' visualisations may have ugly elements. You will need to use your judgement!

## Wrap Up and Share

At the end of this tutorial you'll appoint one member of your group to upload your chosen visualisations to the discussion forum. Alongside your data visualiations share your group's rating of the visualisation on a scale of 1 - 5, where 1 is bad and 5 is good, and why you gave it this rating.

## In your own time

Review the shared visualisations. Comment on another groups visualisation about whether you agree or disagree with the rating and why.

##### This tutorial was adapted from a Hacky Hour coding session run by Krisanat Anukarnsakulchularp and Janith Wanniarachchi.

##### © Copyright 2025 Monash University
